export enum IPC_EVENTS {
  LOAD_ACCOUNTS = 'LOAD_ACCOUNTS',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  ACCOUNT_CHANGE = 'ACCOUNT_CHANGE',
  GET_ACCOUNT = 'GET_ACCOUNT',
  GET_SPEED_DIALS = 'GET_SPEED_DIALS',
  OPEN_SPEEDDIALS_PAGE = 'OPEN_SPEEDDIALS_PAGE',
  GET_LAST_CALLS = 'GET_LAST_CALLS',
  OPEN_ALL_CALLS_PAGE = 'OPEN_ALL_CALLS_PAGE',
  OPEN_ADD_TO_PHONEBOOK_PAGE = 'OPEN_ADD_TO_PHONEBOOK_PAGE',
  CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT'
}
