name: Build and Release Dev

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Get tag name without extra info
        uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ steps.previoustag.outputs.tag }}
          separator: "."
          maxsplit: -1

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Push tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag with this input.
          # Default: 'latest'
          ref: ${{ steps.branch.outputs._0 }}dev${{ steps.vars.outputs.sha_short }}
