name: Build and Release Dev

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get Previous tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Get tag name without extra info
        uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ steps.get-latest-tag.outputs.tag }}
          separator: "dev"
          maxsplit: -1

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Push Git Tag
        run: |
          git config user.name "NethBot"
          git config user.email "NethBot@users.noreply.github.com"
          git commit --allow-empty -m '${{ steps.branch.outputs._0 }}.dev.${{ steps.vars.outputs.sha_short }}'
          git tag ${{ steps.branch.outputs._0 }}.dev.${{ steps.vars.outputs.sha_short }}
          git push origin dev --tags
