name: Bump Homebrew Cask PR

on:
  release:
    types:
      - edited
  workflow_dispatch:

jobs:
  homebrew-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release version
        run: |
          # Extract tag
          TAG_NAME="${{ github.event.release.tag_name }}"
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME=$(git fetch --tags && git describe --tags $(git rev-list --tags --max-count=1))
          fi

          # Remove 'v' before tag
          VERSION=$(echo "$TAG_NAME" | sed 's/^v//')

          echo "Release version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: nethlink
          formula-path: Casks/n/nethlink.rb
          homebrew-tap: Homebrew/homebrew-cask
          tag-name: ${{ env.VERSION }}
          download-url: https://github.com/NethServer/nethlink/releases/download/v${{ env.VERSION }}/nethlink-${{ env.VERSION }}.dmg
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}