name: Bump Winget PR

on:
  release:
    types:
      - edited
  workflow_dispatch:

jobs:
  winget-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: |
          # Extract tag
          TAG_NAME="${{ github.event.release.tag_name }}"
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME=$(git fetch --tags && git describe --tags $(git rev-list --tags --max-count=1))
          fi

          # Remove 'v' before tag
          VERSION=$(echo "$TAG_NAME" | sed 's/^v//')

          echo "Release version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use winget-releaser to create a PR
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: "NethServer.NethLink"
          version: ${{ env.VERSION }}
          token: ${{ secrets.WINGET_GITHUB_TOKEN }}
          fork-user: edospadoni